const datos = {
  Aguas: {
    nombre: "Aguas",
    imagen: "asset/img/aguas.jpg",
    alt: "Categoría de Aguas",
    productos: [
      {
        id: 1,
        nombre: "Bezoya",
        imagen: "asset/img/Bezoya.jpg",
        alt: "Agua Bezoya",
        precio: 1.5,
      },
      {
        id: 2,
        nombre: "Mondariz",
        imagen: "asset/img/Modariz.jpg",
        alt: "Mondariz",
        precio: 1.5,
      },
      {
        id: 3,
        nombre: "Sierra Fría",
        imagen: "asset/img/sierraFria.jpg",
        alt: "Sierra Fría",
        precio: 1.6,
      },
      {
        id: 4,
        nombre: "Solan de Cabras",
        imagen: "asset/img/solanDeCabras.png",
        alt: "Solan de Cabras",
        precio: 1.8,
      },
      {
        id: 5,
        nombre: "Vichy Catalan",
        imagen: "asset/img/vichyCatalan.jpg",
        alt: "Vichy Catalan",
        precio: 2.0,
      },
    ],
  },
  Refrescos: {
    nombre: "Refrescos",
    imagen: "asset/img/refrescos.jpg",
    alt: "Categoría de Refrescos",
    productos: [
      {
        id: 6,
        nombre: "Coca Cola",
        imagen: "asset/img/CocaCola.jpg",
        alt: "Coca Cola",
        precio: 1.8,
      },
      {
        id: 7,
        nombre: "Coca Cola Light",
        imagen: "asset/img/CocaColaLight.jpg",
        alt: "Coca Cola Light",
        precio: 1.8,
      },
      {
        id: 8,
        nombre: "Coca Cola Zero",
        imagen: "asset/img/CocaColaZero.png",
        alt: "Coca Cola Zero",
        precio: 1.8,
      },
      {
        id: 9,
        nombre: "Coca Cola Zero sin Cafeína",
        imagen: "asset/img/CocaColaZeroSinCafeina.png",
        alt: "Coca Cola Zero sin Cafeína",
        precio: 1.8,
      },
      {
        id: 10,
        nombre: "Kas Naranja",
        imagen: "asset/img/KasNaranja.jpg",
        alt: "Kas Naranja",
        precio: 1.7,
      },
      {
        id: 11,
        nombre: "Kas Limón",
        imagen: "asset/img/kasLimon.jpg",
        alt: "Kas Limón",
        precio: 1.7,
      },
      {
        id: 12,
        nombre: "BiFrutas Tropical",
        imagen: "asset/img/biFrutasTropical.png",
        alt: "BiFrutas Tropical",
        precio: 2.0,
      },
    ],
  },
  Cervezas: {
    nombre: "Cervezas",
    imagen: "asset/img/cervezas.jpg",
    alt: "Categoría de Cervezas",
    productos: [
      {
        id: 13,
        nombre: "Estrella Damm",
        imagen: "asset/img/estrellaDamm.jpg",
        alt: "Estrella Damm",
        precio: 2.5,
      },
      {
        id: 14,
        nombre: "Estrella Galicia",
        imagen: "asset/img/estrellaGalicia.png",
        alt: "Estrella Galicia",
        precio: 2.5,
      },
      {
        id: 15,
        nombre: "1906",
        imagen: "asset/img/estrellaG1906.jpg",
        alt: "Estrella Galicia 1906",
        precio: 2.8,
      },
      {
        id: 16,
        nombre: "Heineken",
        imagen: "asset/img/Heineken.jpg",
        alt: "Heineken",
        precio: 2.5,
      },
      {
        id: 17,
        nombre: "Guinness",
        imagen: "asset/img/Guiness.jpg",
        alt: "Guinness",
        precio: 3.0,
      },
    ],
  },
  Cafes: {
    nombre: "Cafes",
    imagen: "asset/img/cafes.jpg",
    alt: "Categoría de Cafés",
    productos: [],
  },
  Licores: {
    nombre: "Licores",
    imagen: "asset/img/licores.jpg",
    alt: "Categoría de Licores",
    productos: [
      {
        id: 18,
        nombre: "Ballantines",
        imagen: "asset/img/Ballantines.png",
        alt: "Ballantines",
        precio: 5.0,
      },
      {
        id: 19,
        nombre: "Ron Cacique",
        imagen: "asset/img/ronCacique.jpg",
        alt: "Ron Cacique",
        precio: 4.5,
      },
      {
        id: 20,
        nombre: "Martini",
        imagen: "asset/img/Martini.png",
        alt: "Martini",
        precio: 4.0,
      },
    ],
  },
  Whisky: {
    nombre: "Whisky",
    imagen: "asset/img/wiskies.jpg",
    alt: "Categoría de Whisky",
    productos: [],
  },
  Vinos: {
    nombre: "Vinos",
    imagen: "asset/img/vinos.jpg",
    alt: "Categoría de Vinos",
    productos: [],
  },
  Cocktails: {
    nombre: "Cocktails",
    imagen: "asset/img/cocktails.jpg",
    alt: "Categoría de Cocktails",
    productos: [],
  },
  Ensaladas: {
    nombre: "Ensaladas",
    imagen: "asset/img/ensaladas.jpg",
    alt: "Categoría de Ensaladas",
    productos: [],
  },
  Tapas: {
    nombre: "Tapas",
    imagen: "asset/img/tapas.jpg",
    alt: "Categoría de Tapas",
    productos: [],
  },
  Bocadillos: {
    nombre: "Bocadillos",
    imagen: "asset/img/bocadillos.jpg",
    alt: "Categoría de Bocadillos",
    productos: [],
  },
  Pescados: {
    nombre: "Pescados",
    imagen: "asset/img/pescados.jpg",
    alt: "Categoría de Pescados",
    productos: [],
  },
  "Platos Elaborados": {
    nombre: "Platos Elaborados",
    imagen: "asset/img/platosElab.jpg",
    alt: "Categoría de Platos Elaborados",
    productos: [],
  },
  Carnes: {
    nombre: "Carnes",
    imagen: "asset/img/carnes.jpg",
    alt: "Categoría de Carnes",
    productos: [],
  },
  "Comida Rápida": {
    nombre: "Comida Rápida",
    imagen: "asset/img/comidaRap.jpg",
    alt: "Categoría de Comida Rápida",
    productos: [],
  },
  Helados: {
    nombre: "Helados",
    imagen: "asset/img/helados.jpg",
    alt: "Categoría de Helados",
    productos: [],
  },
  Combinados: {
    nombre: "Combinados",
    imagen: "asset/img/combi.jpg",
    alt: "Categoría de Combinados",
    productos: [],
  },
  Desayunos: {
    nombre: "Desayunos",
    imagen: "asset/img/desayunos.jpg",
    alt: "Categoría de Desayunos",
    productos: [],
  },
};
